// AUTO-GENERATED by scripts/generate-registry.ts — do not edit by hand.
// Run `npm run generate` (or build) to refresh after adding/removing an icon.
import type { IconSource } from "@/lib/icon-sources";

import { bellPaths } from "@/icons/bell/paths";
import bellSpec from "@/icons/bell/animation.spec";
import { metadata as bellMeta } from "@/icons/bell/metadata";
import { checkPaths } from "@/icons/check/paths";
import checkSpec from "@/icons/check/animation.spec";
import { metadata as checkMeta } from "@/icons/check/metadata";
import { clockPaths } from "@/icons/clock/paths";
import clockSpec from "@/icons/clock/animation.spec";
import { metadata as clockMeta } from "@/icons/clock/metadata";
import { downloadPaths } from "@/icons/download/paths";
import downloadSpec from "@/icons/download/animation.spec";
import { metadata as downloadMeta } from "@/icons/download/metadata";
import { heartPaths } from "@/icons/heart/paths";
import heartSpec from "@/icons/heart/animation.spec";
import { metadata as heartMeta } from "@/icons/heart/metadata";
import { loaderPaths } from "@/icons/loader/paths";
import loaderSpec from "@/icons/loader/animation.spec";
import { metadata as loaderMeta } from "@/icons/loader/metadata";
import { searchPaths } from "@/icons/search/paths";
import searchSpec from "@/icons/search/animation.spec";
import { metadata as searchMeta } from "@/icons/search/metadata";
import { userPaths } from "@/icons/user/paths";
import userSpec from "@/icons/user/animation.spec";
import { metadata as userMeta } from "@/icons/user/metadata";

/** Every icon's framework-agnostic source (pure data — no React). */
export const ICON_SOURCES: Record<string, IconSource> = {
  "bell": { paths: bellPaths, spec: bellSpec, metadata: bellMeta },
  "check": { paths: checkPaths, spec: checkSpec, metadata: checkMeta },
  "clock": { paths: clockPaths, spec: clockSpec, metadata: clockMeta },
  "download": { paths: downloadPaths, spec: downloadSpec, metadata: downloadMeta },
  "heart": { paths: heartPaths, spec: heartSpec, metadata: heartMeta },
  "loader": { paths: loaderPaths, spec: loaderSpec, metadata: loaderMeta },
  "search": { paths: searchPaths, spec: searchSpec, metadata: searchMeta },
  "user": { paths: userPaths, spec: userSpec, metadata: userMeta },
};
