/**
 * Scans icons/*\/ and generates the icon registries so adding an icon never
 * requires editing a registry by hand. Drop a folder under icons/ containing
 * paths.ts + animation.spec.ts + metadata.ts + index.ts and run this (it runs
 * automatically before `dev`, `build`, and `build:cli`).
 *
 * It writes two files:
 *   lib/icon-sources.generated.ts   — pure data (paths + spec + metadata).
 *                                      Bundled into the CLI; never pulls in React.
 *   lib/icon-manifest.generated.ts  — metadata + lazy component imports for the
 *                                      website. Pulls in the React components.
 */
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const REQUIRED = ["paths.ts", "animation.spec.ts", "metadata.ts", "index.ts"];

/** camelCase from a slug, e.g. "arrow-right" → "arrowRight". */
function toCamel(slug: string): string {
  return slug
    .split("-")
    .map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join("");
}

/** Discover every icon folder that has the required source files. */
function discoverSlugs(iconsDir: string): string[] {
  return readdirSync(iconsDir)
    .filter((entry) => {
      const dir = join(iconsDir, entry);
      if (!statSync(dir).isDirectory()) return false;
      return REQUIRED.every((f) => existsSync(join(dir, f)));
    })
    .sort();
}

const HEADER = `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit by hand.
// Run \`npm run generate\` (or build) to refresh after adding/removing an icon.
`;

function buildSourcesFile(slugs: string[]): string {
  const imports = slugs
    .map((slug) => {
      const c = toCamel(slug);
      return [
        `import { ${c}Paths } from "@/icons/${slug}/paths";`,
        `import ${c}Spec from "@/icons/${slug}/animation.spec";`,
        `import { metadata as ${c}Meta } from "@/icons/${slug}/metadata";`,
      ].join("\n");
    })
    .join("\n");

  const entries = slugs
    .map((slug) => {
      const c = toCamel(slug);
      return `  "${slug}": { paths: ${c}Paths, spec: ${c}Spec, metadata: ${c}Meta },`;
    })
    .join("\n");

  return `${HEADER}import type { IconSource } from "@/lib/icon-sources";

${imports}

/** Every icon's framework-agnostic source (pure data — no React). */
export const ICON_SOURCES: Record<string, IconSource> = {
${entries}
};
`;
}

function buildManifestFile(slugs: string[]): string {
  const imports = slugs
    .map((slug) => {
      const c = toCamel(slug);
      return [
        `import { metadata as ${c}Meta } from "@/icons/${slug}/metadata";`,
        `import ${c}Spec from "@/icons/${slug}/animation.spec";`,
      ].join("\n");
    })
    .join("\n");

  // `defaultTrigger` lives in the spec (the framework-agnostic source of truth),
  // so it's merged into each metadata entry here rather than duplicated in
  // metadata.ts.
  const metaEntries = slugs
    .map((slug) => {
      const c = toCamel(slug);
      return `  "${slug}": { ...${c}Meta, defaultTrigger: ${c}Spec.defaultTrigger },`;
    })
    .join("\n");

  const importEntries = slugs
    .map((slug) => `  "${slug}": () => import("@/icons/${slug}"),`)
    .join("\n");

  return `${HEADER}import type { ComponentType } from "react";
import type { IconMetadata, IconProps } from "@/lib/icon-registry";

${imports}

/** Metadata for every icon, keyed by slug. */
export const ICON_METADATA: Record<string, IconMetadata> = {
${metaEntries}
};

/** Lazy component loaders keyed by slug (one chunk per icon). */
export const ICON_IMPORTS: Record<
  string,
  () => Promise<{ default: ComponentType<IconProps> }>
> = {
${importEntries}
};
`;
}

/** Generate both registry files; returns the discovered slugs. */
export function generateRegistry(root: string): string[] {
  const iconsDir = join(root, "icons");
  const slugs = discoverSlugs(iconsDir);
  if (slugs.length === 0) {
    throw new Error(`No icons found in ${iconsDir}`);
  }
  writeFileSync(join(root, "lib", "icon-sources.generated.ts"), buildSourcesFile(slugs));
  writeFileSync(join(root, "lib", "icon-manifest.generated.ts"), buildManifestFile(slugs));
  return slugs;
}

// Run when invoked directly (tsx scripts/generate-registry.ts).
const invokedPath = process.argv[1] ? resolve(process.argv[1]) : "";
const selfPath = fileURLToPath(import.meta.url);
if (invokedPath === selfPath) {
  const root = resolve(dirname(selfPath), "..");
  const slugs = generateRegistry(root);
  console.log(
    `\x1b[32m✓ Generated registries for ${slugs.length} icons:\x1b[0m ${slugs.join(", ")}`,
  );
}
